const legalServices = [
  "Divorce",
  "Land Settlement",
  "Corporate Law",
  "Criminal Defense",
  "Family Law",
  "Intellectual Property",
  "Labor Law",
  "Immigration Law",
  "Tax Law",
  "Personal Injury",
  "Environmental Law",
  "Contract Law",
  "Consumer Protection",
  "Constitutional Law",
  "Banking and Finance Law",
  "Cyber Law",
  "Insurance Law",
  "Real Estate Law",
  "Administrative Law",
  "Education Law",
  "Human Rights Law",
  "Public Interest Litigation",
  "Media and Entertainment Law",
  "Civil Litigation",
  "Property Inheritance",
  "Notary and Documentation",
  "Pro Bono Services",
  "Legal Aid for Marginalized Groups",
  "Juvenile Justice",
  "Anti-Corruption Law",
  "Elder Law",
  "Health Law",
  "Bankruptcy and Insolvency",
  "Customs and Excise Law",
  "Mediation and Arbitration",
];

export default legalServices;
